# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: social_tokenizer 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "social_tokenizer"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Karen Lundgren"]
  s.date = "2014-05-27"
  s.description = "Tokenizes strings for use in social applications."
  s.email = "karen.e.lundgren@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".coveralls.yml",
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "cucumber.yml",
    "features/social_tokenizer.feature",
    "features/step_definitions/social_tokenizer_steps.rb",
    "features/support/env.rb",
    "lib/generators/social_tokenizer/install/install_generator.rb",
    "lib/generators/social_tokenizer/install/templates/initializer.rb",
    "lib/generators/social_tokenizer/utils.rb",
    "lib/social_tokenizer.rb",
    "lib/social_tokenizer/configuration.rb",
    "lib/social_tokenizer/token.rb",
    "lib/social_tokenizer/token_type.rb",
    "lib/social_tokenizer/tokenizer.rb",
    "lib/social_tokenizer/version.rb",
    "social_tokenizer.gemspec"
  ]
  s.homepage = "http://www.gemvein.com/museum/cases/social_tokenizer"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Tokenizes strings for use in social applications."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, [">= 4.1"])
      s.add_runtime_dependency(%q<tokenizer>, [">= 0"])
      s.add_runtime_dependency(%q<social_tokenizer>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<coveralls>, [">= 0"])
    else
      s.add_dependency(%q<activemodel>, [">= 4.1"])
      s.add_dependency(%q<tokenizer>, [">= 0"])
      s.add_dependency(%q<social_tokenizer>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<coveralls>, [">= 0"])
    end
  else
    s.add_dependency(%q<activemodel>, [">= 4.1"])
    s.add_dependency(%q<tokenizer>, [">= 0"])
    s.add_dependency(%q<social_tokenizer>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<coveralls>, [">= 0"])
  end
end

