# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bd4bab964f83b591fa5408479d86b3ca3420f20d0ce7e44d46ac2ccac03466008fe947969cb91454c115605a3ca886339a1a42bec71ca83f282a5f328c23d5f

test:
  secret_key_base: 465ddf64cb6d1b9f94eb27c2afdfd357c18d5eb883d0468b47838bea4a6c4034da637b1c2bd7034b23ab5edfe07f5d0ef13aa6375e048cdbb628b4a9440a0589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
